/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface": "#2f3331",
        "secondary-fixed-dim": "#dbd3c8",
        "surface-container-lowest": "#ffffff",
        "tertiary-dim": "#54534f",
        "on-primary-fixed": "#433f38",
        "on-error": "#fff7f6",
        "inverse-on-surface": "#9d9d9b",
        "secondary-container": "#e9e2d6",
        "surface-container-high": "#e6e9e6",
        "inverse-surface": "#0d0e0e",
        "surface-container-highest": "#e0e3e0",
        "outline-variant": "#afb3b0",
        secondary: "#635f56",
        "on-error-container": "#742410",
        "on-background": "#2f3331",
        "on-primary-fixed-variant": "#605b53",
        "surface-tint": "#635e56",
        "surface-dim": "#d6dbd7",
        "on-secondary-container": "#555149",
        "error-dim": "#5c1202",
        "on-tertiary-container": "#5d5c57",
        "primary-container": "#eae1d7",
        "inverse-primary": "#f8efe5",
        "on-secondary-fixed-variant": "#5f5b52",
        error: "#9e422c",
        "tertiary-fixed-dim": "#e8e5df",
        "error-container": "#fe8b70",
        "tertiary-container": "#f6f3ed",
        "secondary-dim": "#57534a",
        "primary-fixed-dim": "#dcd3ca",
        tertiary: "#605f5a",
        "on-primary-container": "#56514a",
        "on-tertiary": "#fcf9f2",
        surface: "#faf9f7",
        "on-secondary": "#fff8ee",
        "on-primary": "#fff6ed",
        primary: "#635e56",
        "on-tertiary-fixed": "#4a4a45",
        outline: "#777c79",
        "surface-container": "#edeeeb",
        "on-secondary-fixed": "#433f37",
        background: "#faf9f7",
        "tertiary-fixed": "#f6f3ed",
        "on-tertiary-fixed-variant": "#676661",
        "on-surface-variant": "#5c605d",
        "surface-container-low": "#f4f4f1",
        "surface-variant": "#e0e3e0",
        "primary-fixed": "#eae1d7",
        "primary-dim": "#57524a",
        "secondary-fixed": "#e9e2d6",
        "surface-bright": "#faf9f7",
      },
      fontFamily: {
        headline: ["Noto Serif", "serif"],
        body: ["Manrope", "system-ui", "sans-serif"],
        label: ["Manrope", "system-ui", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};
